# Generated by Django 3.2.15 on 2022-09-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('shelf_quantity', models.IntegerField()),
                ('shelf_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store_quantity', models.IntegerField()),
                ('note', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='inventoryImages')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('client_code', models.CharField(max_length=9)),
                ('formatted_address', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_title', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
                ('chain', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('credit', 'credit')], default='cash', max_length=50)),
                ('geofencing_radius', models.FloatField()),
                ('credit_limit', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('latest_visit', models.DateTimeField()),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('is_chain', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10000)),
                ('field_type', models.CharField(default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('force_sequence', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50)),
                ('force_sequence', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('project', models.ManyToManyField(to='adhoc_mobile.Project')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_duration', models.TimeField()),
                ('store_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('start_distance', models.CharField(max_length=50)),
                ('end_distance', models.CharField(max_length=50)),
                ('delta_distance', models.FloatField()),
                ('start_in_geofence', models.BooleanField(default=False)),
                ('end_in_geofence', models.BooleanField(default=False)),
                ('auto_closed_by_geofence', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ManyToManyField(to='adhoc_mobile.Route')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('weekly', 'weekly'), ('daily', 'daily'), ('monthly', 'monthly')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('occurrences', models.IntegerField()),
                ('note', models.CharField(max_length=50)),
                ('force_sequence', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.plan', to_field='name')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.project')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='route',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.rule'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.area')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('local_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=10)),
                ('barcode', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('retailSelling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand', models.CharField(max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('measure_unit', models.CharField(max_length=50)),
                ('auditable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('frozen_preSale', models.BooleanField(default=False)),
                ('frozen_sale', models.BooleanField(default=False)),
                ('exp_date', models.DateTimeField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('audit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.audit')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.category', to_field='name')),
                ('client', models.ManyToManyField(to='adhoc_mobile.Client')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.project')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.project'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50)),
                ('image_type', models.CharField(choices=[('1', 'before'), ('2', 'after'), ('3', 'regular')], default='3', max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='stores/')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.visit')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('field', models.ManyToManyField(related_name='fields', to='adhoc_mobile.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('isDisabled', models.BooleanField(default=False)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('phone', models.CharField(max_length=11)),
                ('forceOnlineConnectivity', models.BooleanField(default=False)),
                ('job_option', models.CharField(choices=[('1', 'data collector'), ('2', 'merchandiser'), ('3', 'back office'), ('4', 'supervisor'), ('5', 'admin')], max_length=50)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.project'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.region', to_field='name'),
        ),
        migrations.AddField(
            model_name='client',
            name='route',
            field=models.ManyToManyField(to='adhoc_mobile.Route'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date/Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date/Time')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.country')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.visit'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.city'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000)),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to', to='adhoc_mobile.field')),
            ],
        ),
    ]
