# Generated by Django 3.2.15 on 2022-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0002_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='extra_field',
            field=models.ImageField(blank=True, upload_to='stores/'),
        ),
    ]
