# Generated by Django 3.2.15 on 2022-09-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0003_answer_extra_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='extra_field',
        ),
    ]
