# Generated by Django 3.2.15 on 2022-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0008_auto_20220927_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
