# Generated by Django 3.2.15 on 2022-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0009_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='products/'),
        ),
    ]
