# Generated by Django 3.2.15 on 2022-09-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0010_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
