# Generated by Django 3.2.15 on 2022-09-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0011_auto_20220928_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='client',
        ),
    ]
