# Generated by Django 3.2.15 on 2022-09-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc_mobile', '0012_auto_20220928_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adhoc_mobile.audit'),
        ),
    ]
